### PR TITLE
Fix Travis CI build

### PR DESCRIPTION
**Pull request by peter279k**
As title, fix the Travis CI build. And this test will be passed in Travis CI build :+1:.

### CODE REVIEW

**Comment by JordanRL** [comment]
Thanks for the contribution. I'm going to take a look at the assert that was changed before I accept the PR, just to make sure it doesn't change what the test is testing.

**Comment by peter279k** [comment]
Hi @JordanRL, thank you for your reply. Please check that work you mention.

If having any problem, please feel free to add the comment on pull requests :).

**Comment by peter279k** [comment]
Is any update about this PR?

**Comment by JordanRL** [comment]
Sorry @peter279k work has been a little crazy since the new year. Thank you very, very much for this contribution, I greatly appreciate it, and I'm sorry it took so long to approve the PR.

**Comment by peter279k** [comment]
Hi  @JordanRL, thank you for your reply.

I hope you can concern this and merge this PR finally :).

Let me have the chance to contribute your projects on GitHub in the future if possible :).

**Pull request merged**
